### ISSUE TITLE
Images for Learn HTML & CSS: Part I

### ISSUE THREAD

**Issue by thieunguyenhauet** [truonganhhoang/INT2208-1-2017#1]
Completed
![bandicam 2017-02-12 17-36-52-007](https://cloud.githubusercontent.com/assets/25699875/22864416/a17e853e-f183-11e6-829b-0bd87357ce71.jpg)
![bandicam 2017-02-13 00-31-55-265](https://cloud.githubusercontent.com/assets/25699875/22864426/dd0aff4c-f183-11e6-9e79-9ca95b7bc9cc.jpg)

**Comment by truonganhhoang** [comment]
ko phải nộp ở issue này.
