### ISSUE TITLE
Bài tập dự án của các nhóm 

### ISSUE THREAD

**Issue by truonganhhoang** [truonganhhoang/INT2208-1-2017#116]
1. Các nhóm thảo luận để chọn một ứng dụng đơn giản, làm lại nó. Gợi ý: dùng các dự án có trong slide số 0, hoặc chọn một số app phục vụ giáo dục thuộc top trên Google Play Store, Apple App Store, làm phiên bản web cho app đó.

2. Sau khi thống nhất dự án trong nhóm, thiết kế ít nhất mỗi người 1 màn hình giao diện, chọn các màn hình giao diện quan trọng nhất của ứng dụng làm trước, với đầy đủ chi tiết bằng một số công cụ thiết kế giao diện dựa trên bootstrap framework. Gợi ý, tìm trên google với từ khóa: bootstrap mockup để tìm một công cụ để làm giao diện cho ứng dụng của nhóm.

3. Làm tài liệu thuyết trình ứng dụng bằng file markdown với tên: readme.md và để trong thư mục với tên thư mục là Nhom-<tên của nhóm>. Gợi ý, có thể sử dụng paper.dropbox.com để các thành viên trong nhóm cùng soạn thảo được đồng thời, rồi xuất ra file markdown để nộp vào github. Trưởng nhóm tạo pull request sau khi hoàn thành bài tập nhóm.

Yêu thêm cho các nhóm về bài tập nhóm:

1. Mỗi người làm ít nhất một màn hình chức năng chính của dự án nhóm bằng bootstrap thuần, không sử dụng thêm các css riêng. Không hardcode trong html.

2. Đặt tên các files ảnh màn hình sau khi thiết kế kèm theo mã html bằng các file 1.jpg 1.html, 2.jpg, 2.html, v.v.. vào thư mục của nhóm. Trong file html, link đến file bootstrap trên mạng (bootstrap cdn).

3. Để hạn chế pull requests, các nhóm sẽ nộp bài vào repo của trưởng nhóm, sau đó trưởng nhóm tạo pull request để nộp bài của cả nhóm cho giáo viên.

Hạn: 8/3/2017. Ngày 9/3 sẽ chấm điểm.

Chú ý: Ngoài ra, các thành viên trong nhóm kiểm tra chéo bài tập về nhà cá nhân của nhau, điểm sẽ chấm dựa trên bài kém nhất của cả nhóm.

**Comment by truonganhhoang** [comment]
# Chấm điểm chéo giữa các nhóm

Các nhóm hoàn thiện bài tập nhóm đến hết ngày 10/3/2017. Từ 11-12/3 các nhóm chấm điểm nhóm khác và viết nhận xét về các nhóm khác bằng cách comment vào issue này dựa trên thứ tự các nhóm trong danh sách dưới đây, nhóm trên chấm nhóm dưới, nhóm cuối cùng chấm nhóm đầu tiên. Điểm của người thấp nhất 50%, điểm bài tập dự án của nhóm 50%, chấm theo các yêu cầu đã nêu của issue như file readme.md, các ảnh màn hình và html có theo qui định không, và chất lượng của các comments khi commits. Nhập điểm vào cột Q ở file Google Sheet danh sách lớp.

TTMD
Sketters
PhpStorm
PCandmore
OMYBET
MT-P
HAI
FAM
CTA
CHHĐ
C3H
BETEZ
20GG

**Comment by NgoHaiYen** [comment]
thầy ơi nhóm em bị conflict file chưa pull được lên thì tính thế nào ạ? T_T

**Comment by truonganhhoang** [comment]
Nhóm em tìm cách sửa sớm đi..

**Comment by luongquy08** [comment]
Thưa thầy, em có hỏi thầy về việc có được sử dụng thêm css để style cho giao diện mềm dẻo hơn được không. Thầy bảo có thể nhưng thầy không khuyến khích sử dụng. Vậy yêu cầu chỉ được dùng bootstrap thuần, không sử dụng thêm css ngoài có dùng để chấm điểm nữa không ạ?

**Comment by truonganhhoang** [comment]
Nếu các em thấy rất cần và hiểu vc mình làm là đúng thì có thể làm.. chứ ko
nê  trang trí mà ko có cơ sở nhé.

**Comment by rungtrucxanh1997** [comment]
Nhận xét nhóm 20GG: Các thành viên làm bài tập cá nhân  đầy đủ (Trên github hiện tại không đủ file do ai đó commit lỗi, phải xem lại history), nhóm có ý tưởng sáng tạo, tên file đặt chính xác, đủ file và commit đầy đủ, tuy nhiên commit chưa thực sự sát nội dung, và file ảnh demo nên để ở định dạng .jpg

**Comment by luongquy08** [comment]
Nhận xét nhóm PHPStorm:
- Ưu điểm:
+ Các thành viên có ý thức làm bài tập đầy đủ.
+ Bài tập lớn: Các file ảnh, file html đặt theo yêu cầu.
- Khuyết điểm:
+ Bài tập cá nhân còn đặt sai tên ảnh, comment chất lượng thấp.

**Comment by tdviet97** [comment]
Nhóm 20GG nhận xét bài cả nhóm TTMD
* Về bài tập nhóm
-	Phần commit : commit không có ý nghĩa
-	Nội dung
+ Đặt tên các ảnh sai quy tắc(không có số thứ tự)
+ Chưa tập trung vào công việc cần làm
* Về bài tập cá nhân
-	Các thành viên làm bài tập đầy đủ
-	Đặt tên file đúng yêu cầu
-	Commit chưa thực sự tốt

**Comment by hanhpth27** [comment]
Nhóm C3H nhận xét bài cả nhóm BETEZ:
- Ưu điểm: 
      + Các thành viên làm bài tập đầy đủ
      + Phần commit ở bài tập hàng tuần đã đúng theo quy cách
      + Bài tập nhóm đã đặt theo yêu cầu
- Khuyết điểm:
      + Còn 1 bạn đặt tên sai quy cách ( Vu Tuan Thanh) 
      + Đặt sai tên ảnh ở bài tập cá nhân (NguyenNangTung)

**Comment by hoanganhit1997** [comment]
Nhóm HAI nhận xét bài cả nhóm FAM:

- Ưu điểm:
+ Các thành viên làm bài tập đầy đủ
+ Phần commit ở bài tập cá nhân phần lớn đúng quy cách 
+ Bài tập nhóm đầy đủ
- Khuyết điểm:
+ Phần commit bài tập nhóm sai yêu cầu (tiếng việt)
+ Commit bài tập về nhà của Đinh Khắc Quý khó hiểu 
+ Ảnh của bài tập nhóm k để đúng định dạng .jpg

**Comment by conmangangqua** [comment]
Nhóm OMYBET nhận xét bài cả nhóm M-TP:
- Về bài tập cá nhân : 
1 . Đỗ Hoàng Linh không có ảnh phần HTML&CSS
2 . Phạm Đức Lưu không có bài
3 . Commit đúng cách
- Về bài tập lớn : 
1 . Chưa đủ 4 giao diện
2 . Đặt tên file html và commit đúng cách
3 . Ảnh chưa để định dạng .jpg
4 . Chưa xóa file thừa ( Nhom-MTP )

**Comment by QuocCuongUET** [comment]
Nhận xét của nhóm CTA đối với nhóm CHHD
 Về bài tập Nhóm:
	-Tên file đặt chưa chính xác 
	-Commit sát nội dung. Nếu viết tiếng việt thì tốt hơn
	-Thừa file readme
	-
* Về bài tập cá nhân:
	-Làm bài tập đầy đủ tuy nhiên commit  chất lượng thấp

**Comment by NgoHaiYen** [comment]
Nhận xét của nhóm FAM về nhóm CTA:
Về bài tập hàng tuần:
- bài tập chưa đầy đủ: 
    +Khoa Văn Chính: thiếu bài tập tuần 3, 4, bài tập tuần một thiếu git, bài tập tuần 2 thiếu jquery và makeawebsite
    + Lê Huy Cường: bài tập đầy đủ nhưng chỉ comment tuần 3 và tuần 4
    + Nguyễn Văn Thu: thiếu bài tập tuần 1, và bài tập jquery chưa hoàn thành
    + Quản Quốc Thịnh: mới có bài tập tuần 1 là git và html
Về bài tập nhóm: làm bài tập đầy đủ nhưng bị lỗi font chữ

**Comment by yosenju238** [comment]
Nhận xét của nhóm TTMD về nhóm Sketters:
Lưu ý đầu tiên là trong readme.md chưa đề cập đến các thành viên nhóm ngoài nhóm trưởng tuy rằng bạn có đề cập đến tên thành viên trong file mô tả công việc.
Bài tập cá nhân: đầy đủ (bạn Hà Văn Linh lưu ý không có ảnh jQuery nhưng trong các ảnh khác thì cho thấy khóa học đã hoàn tất).
Bài tập nhóm:
+ Mình bất ngờ là nhóm bạn đã có thể truy cập với địa chỉ online: thionline.freevnn.com
+ Hơi vượt quá yêu cầu là đã sử dụng thêm css riêng.
+ Không hiểu lắm khi nhóm bạn sử dụng 2 file readme.md với nội dung khá tương tự nhau.
+ Ngoài ra commit, tên file và nội dung đều xuất sắc.

**Comment by luongquy08** [comment]
Cảm ơn Tú đã nhận xét về bài tập của nhóm Skeeters.

**Comment by CuongK60UET** [comment]
Nhóm CHHD nhận xét nhóm C3H:

Ưu điểm:
Các thành viên có ý thức làm bài tập đầy đủ.
Bài tập lớn: Các file ảnh, file html đặt theo yêu cầu.
commit khá ổn
Khuyết điểm:
Tên trang phim viết sai ( Movies -> Movise không biết là vô ý hay cố tình)
